soundfontdir: config/sf2
bankdir: config/banks
mfilesdir: config/midi
plugindir: /usr/lib/ladspa
currentbank: bank1.yaml

fluidsettings:
  midi.autoconnect: 1
  player.reset-synth: 0
  synth.ladspa.active: 1
