# default bank w/ a range of useful patches
# requiring only small included fonts plus fluid's GM font
# obtaining FluidGM_R3.sf2:
#  -download from archive.org/details/fluidr3-gm-gs
#  -or link to copy installed w/fluidsynth:
#   `ln -s /usr/share/sounds/sf2/FluidR3_GM.sf2 SquishBox/sf2/`
# Tom's Audio Plugins required for effects:
#   `sudo apt-get install tap-plugins`
# assign CCs 7, 13-16, 91, 93 to knobs/sliders
# assign toggle CCs 27-28 to pads

router_rules:
  - {type: cc, chan: 1=2-16, par1: 7}
  - {type: cc, chan: 1=2-6, par1: 1}
  - {type: cc, chan: 1=2-6, par1: 64}
  - {type: cc, chan: 1=2-6, par1: 91}
  - {type: pbend, chan: 1=2-6}

patches:
  Piano: 
    1: FluidR3_GM.sf2:000:001
  Rhodes: 
    1: FluidR3_GM.sf2:000:004
    2: VintageDreamsWaves-v2.sf2:000:019
    10: FluidR3_GM.sf2:128:032
  FM Piano:
    1: FM Piano.sf2:000:000
  Vibes: 
    1: FluidR3_GM.sf2:000:011
  Tonewheel:
    1: FluidR3_GM.sf2:000:017
    # CC 13-16 controls the leslie effect
    ladspafx:
      Rotary Speaker:
        lib: /usr/lib/ladspa/tap_rotspeak.so
        vals:
          Rotor Freq: 5
          Horn Freq: 8
          Rotor/Horn Mix: 0.5
    router_rules:
    - {type: cc, chan: 1, par1: 13, par2: 0-127=0-30, ladspafx: Rotary Speaker, port: Rotor Freq}
    - {type: cc, chan: 1, par1: 14, par2: 0-127=0-30, ladspafx: Rotary Speaker, port: Horn Freq}
    - {type: cc, chan: 1, par1: 15, par2: 0-127=0-100, ladspafx: Rotary Speaker, port: Mic Dist}
    - {type: cc, chan: 1, par1: 16, par2: 0-127=0-1, ladspafx: Rotary Speaker, port: Rotor/Horn Mix}
  Compy Guitar:
    1: FluidR3_GM.sf2:000:027
  Funk Guitar:
    1: FluidR3_GM.sf2:008:028
  Shred Guitar:
    1: FluidR3_GM.sf2:000:030
    # CC 13, 14 control tube drive, tape/tube mix
    ladspafx:
      Tube Warmth:
        lib: /usr/lib/ladspa/tap_tubewarmth.so
        audio: mono
        vals: {Drive: 2.5, Tape: 10}
    router_rules:
    - {type: cc, chan: 1, par1: 13, par2: 0-127=0.1-10, ladspafx: Tube Warmth, port: Drive}
    - {type: cc, chan: 1, par1: 14, par2: 0-127=-10-10, ladspafx: Tube Warmth, port: Tape}
  Bass+Oct:
    1: FluidR3_GM.sf2:000:033
    3: FluidR3_GM.sf2:000:033
    # CC 27 switches the octave doubling on/off
    router_rules:
    - {type: note, chan: 1=3, par1: 0-127*1-12}
    - {type: cc, chan: 10=3, par1: 27=7, par2: 0-127*127+0}
  Synth Bass:
    1: FluidR3_GM.sf2:000:038
  Sweep Bass:
    1: VintageDreamsWaves-v2.sf2:000:022
  Strings:
    1: FluidR3_GM.sf2:000:048
  Synth Strings:
    1: FluidR3_GM.sf2:000:051
  Synth Voice:
    1: FluidR3_GM.sf2:000:054
  Synth Brass:
    1: FluidR3_GM.sf2:000:062
  Smooth Flute:
    4: FluidR3_GM.sf2:000:073
    router_rules:
    # CC 13, 28 control porta time, on/off
    - {type: note, chan: 1=4, par1: 0-127*1+12}
    - {type: cc, chan: 10=4, par1: 28=65, par2: 0-127*127+0}
    - {type: cc, chan: 10=4, par1: 28=68, par2: 0-127*127+0}
    - {type: cc, chan: 1=4, par1: 13=37, par2: 0-127*1+0}
  Dragon Sweep:
    1: VintageDreamsWaves-v2.sf2:000:006
  Stacked Lead:
    1: VintageDreamsWaves-v2.sf2:000:043
  Mod Synth:
    5: ModSynth_R1.sf2:000:000
    6: ModSynth_R1.sf2:000:000
    router_rules:
    - {type: note, chan: 1-2*1+4}
    - {type: cc, chan: 1=5-6, par1: 13=74} # filter cutoff
    - {type: cc, chan: 1=5-6, par1: 14=78} # modenv attack
    - {type: cc, chan: 1=5-6, par1: 15=79} # modenv decay
    - {type: cc, chan: 1=5-6, par1: 16=82} # modenv -> filter
  Warm Pad:
    1: FluidR3_GM.sf2:000:089
  Sweep Pad:
    1: FluidR3_GM.sf2:000:095
  Analog Pad:
    1: VintageDreamsWaves-v2.sf2:000:102
  NewAge:
    1: FluidR3_GM.sf2:000:097
  SFX:
    11: FluidR3_GM.sf2:000:122
    12: FluidR3_GM.sf2:000:123
    13: FluidR3_GM.sf2:000:124
    14: FluidR3_GM.sf2:000:125
    15: FluidR3_GM.sf2:000:126
    16: FluidR3_GM.sf2:000:127
    router_rules:
    - {type: note, chan: 1=11, par1: C3-E3=C3-C5}
    - {type: note, chan: 1=12, par1: F3-A3=C3-C5}
    - {type: note, chan: 1=13, par1: A#3-D4=C3-C5}
    - {type: note, chan: 1=14, par1: D#4-G4=C3-C5}
    - {type: note, chan: 1=15, par1: G#4-C5=C3-C5}
    - {type: note, chan: 1=16, par1: C#5-F5=C3-C5}
  Standard Kit:
    1: FluidR3_GM.sf2:128:001
    router_rules:
    - {type: note, chan: 10=1}
  Power Kit:
    1: FluidR3_GM.sf2:128:016
    router_rules:
    - {type: note, chan: 10=1}

init:
  messages: [cc:4:37:60, cc:4:65:127, cc:4:68:127,
             cc:5:71:0, cc:5:73:0, cc:5:74:0, cc:5:78:40, cc:5:79:40, cc:5:80:80, cc:5:81:127, cc:5:82:80, 
             cc:5:71:0, cc:5:73:0, cc:5:74:0, cc:5:78:40, cc:5:79:40, cc:5:80:80, cc:5:81:127, cc:5:82:80, 
             cc:6:100:0, cc:6:101:0, cc:6:6:12, cc:6:38:0]
