soundfontdir: fluidpatcher/config/sf2
bankdir: fluidpatcher/config/banks
mfilesdir: fluidpatcher/config/midi
plugindir: /usr/lib/ladspa
currentbank: bank1.yaml

fluidsettings:
  midi.autoconnect: 1
  player.reset-synth: 0
  synth.ladspa.active: 1
